/** Shapes returned by /api/parent/children, shared by Home and Calendar. */

/**
 * An absence entry. The API returns objects, not date strings — `kind`
 * distinguishes a one-off from a day generated by a recurring rule, which
 * matters because only one-offs can be cancelled by tapping the date again.
 */
export type Absence = { date: string; kind: 'one_off' | 'recurring' | string }

export type Child = {
  id: number
  name: string
  school: string
  service_type: string
  registered_days: string[]
  upcoming_absences: Absence[]
  absence_exceptions: unknown[]
  recurring_absences: unknown[]
}

export const WEEKDAYS = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
]

export function isoOf(d: Date): string {
  return `${d.getFullYear()}-${`${d.getMonth() + 1}`.padStart(2, '0')}-${`${d.getDate()}`.padStart(2, '0')}`
}

export function todayIso(): string {
  return isoOf(new Date())
}

export function absenceOn(child: Child, date: string): Absence | undefined {
  return child.upcoming_absences.find((a) => a.date === date)
}

export type TodayState = 'attending' | 'absent' | 'off'

export function stateOn(child: Child, date: string): TodayState {
  const weekday = WEEKDAYS[new Date(`${date}T12:00:00`).getDay()]
  if (!child.registered_days.includes(weekday)) return 'off'
  if (absenceOn(child, date)) return 'absent'
  return 'attending'
}
